---
title: "GitHub Pages Instructions"
author: "Heidi E. Steiner"
date: "2/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


General idea:  
#### Users already have an existing repo on GitHub and want to add a .RMD hosted Hugo themed website to the directory  



### 1. New Project

File new project (new directory), website with blogdown, sub-directory of project working on called website perhaps

### 2. Create `docs/` directory within project root with `mkdir ../docs` in the terminal

We will be copying the `website/public/` to `docs/` and push `docs/` to GitHub when we're ready 

### 3. Create `.noyekyll` within  `docs/` with `file.create('../docs/.nojekyll')` 

This will stop GitHub from being confused that we're using Hugo 

**HINT**: Use `ls -a ../docs/` to double check your `.nojekyll` file was made 

### 4. Prep GitHub repo for page documents 

- Go to `Settings` in your github repo 
- Select `Pages` on the guide on the left of the screen
- Change `Branch` from none to `main` (or `master`) 
- Change repo from root to `docs/`
- Save & Refresh
- Copy the url made for your repo

### 5. Change base url in `config.yaml` to new github pages url 

Paste the url in `config.yaml` as the key to the `baseurl` value

### 6. Add `website/` to `.gitignore` ! This is very important 

Create (or add to an existing `.gitignore`) in the root project. Include all the website materials in the `.gitignore` for now. We don't need to have our website creation materials be public, just the final posts.

### 7. `blogdown::serve_site()` to view progress in viewer 

Make sure everything is working locally...

### 8. `blogdown::build_site()` prior to pushing to GitHub

Building the site will create a `public/` directory within `website/` which we want to copy to `root_project/docs/` to push to GitHub. 

### 9. Copy contents of new `public/` folder to `../docs/` 

This is a manual process so I doubt this is the most efficient way, but this works! 

### 10. Push to existing GitHub repo 

Do all the new files in `public/` show up in your changes? 

### Extra Time. Download new theme and update as desired! 

[A complete list of Hugo themes](https://themes.gohugo.io/)  
[More common (aka more likely to work) Hugo themes via Wowchemy](https://wowchemy.com/hugo-themes/)

